using Toybox.Application;
import Toybox.Lang;

// Auto-generated by scripts/curate_garmin_data.py — do not edit manually.
module BibleResources {

    // Offline coverage: New Testament + Psalms + Proverbs + Genesis 1-10
    // Total chapters: 451

    const GEN_RESOURCES = [
        Rez.JsonData.gen_1,
        Rez.JsonData.gen_2,
        Rez.JsonData.gen_3,
        Rez.JsonData.gen_4,
        Rez.JsonData.gen_5,
        Rez.JsonData.gen_6,
        Rez.JsonData.gen_7,
        Rez.JsonData.gen_8,
        Rez.JsonData.gen_9,
        Rez.JsonData.gen_10,
    ] as Array<ResourceId>;

    const PSA_RESOURCES = [
        Rez.JsonData.psa_1,
        Rez.JsonData.psa_2,
        Rez.JsonData.psa_3,
        Rez.JsonData.psa_4,
        Rez.JsonData.psa_5,
        Rez.JsonData.psa_6,
        Rez.JsonData.psa_7,
        Rez.JsonData.psa_8,
        Rez.JsonData.psa_9,
        Rez.JsonData.psa_10,
        Rez.JsonData.psa_11,
        Rez.JsonData.psa_12,
        Rez.JsonData.psa_13,
        Rez.JsonData.psa_14,
        Rez.JsonData.psa_15,
        Rez.JsonData.psa_16,
        Rez.JsonData.psa_17,
        Rez.JsonData.psa_18,
        Rez.JsonData.psa_19,
        Rez.JsonData.psa_20,
        Rez.JsonData.psa_21,
        Rez.JsonData.psa_22,
        Rez.JsonData.psa_23,
        Rez.JsonData.psa_24,
        Rez.JsonData.psa_25,
        Rez.JsonData.psa_26,
        Rez.JsonData.psa_27,
        Rez.JsonData.psa_28,
        Rez.JsonData.psa_29,
        Rez.JsonData.psa_30,
        Rez.JsonData.psa_31,
        Rez.JsonData.psa_32,
        Rez.JsonData.psa_33,
        Rez.JsonData.psa_34,
        Rez.JsonData.psa_35,
        Rez.JsonData.psa_36,
        Rez.JsonData.psa_37,
        Rez.JsonData.psa_38,
        Rez.JsonData.psa_39,
        Rez.JsonData.psa_40,
        Rez.JsonData.psa_41,
        Rez.JsonData.psa_42,
        Rez.JsonData.psa_43,
        Rez.JsonData.psa_44,
        Rez.JsonData.psa_45,
        Rez.JsonData.psa_46,
        Rez.JsonData.psa_47,
        Rez.JsonData.psa_48,
        Rez.JsonData.psa_49,
        Rez.JsonData.psa_50,
        Rez.JsonData.psa_51,
        Rez.JsonData.psa_52,
        Rez.JsonData.psa_53,
        Rez.JsonData.psa_54,
        Rez.JsonData.psa_55,
        Rez.JsonData.psa_56,
        Rez.JsonData.psa_57,
        Rez.JsonData.psa_58,
        Rez.JsonData.psa_59,
        Rez.JsonData.psa_60,
        Rez.JsonData.psa_61,
        Rez.JsonData.psa_62,
        Rez.JsonData.psa_63,
        Rez.JsonData.psa_64,
        Rez.JsonData.psa_65,
        Rez.JsonData.psa_66,
        Rez.JsonData.psa_67,
        Rez.JsonData.psa_68,
        Rez.JsonData.psa_69,
        Rez.JsonData.psa_70,
        Rez.JsonData.psa_71,
        Rez.JsonData.psa_72,
        Rez.JsonData.psa_73,
        Rez.JsonData.psa_74,
        Rez.JsonData.psa_75,
        Rez.JsonData.psa_76,
        Rez.JsonData.psa_77,
        Rez.JsonData.psa_78,
        Rez.JsonData.psa_79,
        Rez.JsonData.psa_80,
        Rez.JsonData.psa_81,
        Rez.JsonData.psa_82,
        Rez.JsonData.psa_83,
        Rez.JsonData.psa_84,
        Rez.JsonData.psa_85,
        Rez.JsonData.psa_86,
        Rez.JsonData.psa_87,
        Rez.JsonData.psa_88,
        Rez.JsonData.psa_89,
        Rez.JsonData.psa_90,
        Rez.JsonData.psa_91,
        Rez.JsonData.psa_92,
        Rez.JsonData.psa_93,
        Rez.JsonData.psa_94,
        Rez.JsonData.psa_95,
        Rez.JsonData.psa_96,
        Rez.JsonData.psa_97,
        Rez.JsonData.psa_98,
        Rez.JsonData.psa_99,
        Rez.JsonData.psa_100,
        Rez.JsonData.psa_101,
        Rez.JsonData.psa_102,
        Rez.JsonData.psa_103,
        Rez.JsonData.psa_104,
        Rez.JsonData.psa_105,
        Rez.JsonData.psa_106,
        Rez.JsonData.psa_107,
        Rez.JsonData.psa_108,
        Rez.JsonData.psa_109,
        Rez.JsonData.psa_110,
        Rez.JsonData.psa_111,
        Rez.JsonData.psa_112,
        Rez.JsonData.psa_113,
        Rez.JsonData.psa_114,
        Rez.JsonData.psa_115,
        Rez.JsonData.psa_116,
        Rez.JsonData.psa_117,
        Rez.JsonData.psa_118,
        Rez.JsonData.psa_119,
        Rez.JsonData.psa_120,
        Rez.JsonData.psa_121,
        Rez.JsonData.psa_122,
        Rez.JsonData.psa_123,
        Rez.JsonData.psa_124,
        Rez.JsonData.psa_125,
        Rez.JsonData.psa_126,
        Rez.JsonData.psa_127,
        Rez.JsonData.psa_128,
        Rez.JsonData.psa_129,
        Rez.JsonData.psa_130,
        Rez.JsonData.psa_131,
        Rez.JsonData.psa_132,
        Rez.JsonData.psa_133,
        Rez.JsonData.psa_134,
        Rez.JsonData.psa_135,
        Rez.JsonData.psa_136,
        Rez.JsonData.psa_137,
        Rez.JsonData.psa_138,
        Rez.JsonData.psa_139,
        Rez.JsonData.psa_140,
        Rez.JsonData.psa_141,
        Rez.JsonData.psa_142,
        Rez.JsonData.psa_143,
        Rez.JsonData.psa_144,
        Rez.JsonData.psa_145,
        Rez.JsonData.psa_146,
        Rez.JsonData.psa_147,
        Rez.JsonData.psa_148,
        Rez.JsonData.psa_149,
        Rez.JsonData.psa_150,
    ] as Array<ResourceId>;

    const PRO_RESOURCES = [
        Rez.JsonData.pro_1,
        Rez.JsonData.pro_2,
        Rez.JsonData.pro_3,
        Rez.JsonData.pro_4,
        Rez.JsonData.pro_5,
        Rez.JsonData.pro_6,
        Rez.JsonData.pro_7,
        Rez.JsonData.pro_8,
        Rez.JsonData.pro_9,
        Rez.JsonData.pro_10,
        Rez.JsonData.pro_11,
        Rez.JsonData.pro_12,
        Rez.JsonData.pro_13,
        Rez.JsonData.pro_14,
        Rez.JsonData.pro_15,
        Rez.JsonData.pro_16,
        Rez.JsonData.pro_17,
        Rez.JsonData.pro_18,
        Rez.JsonData.pro_19,
        Rez.JsonData.pro_20,
        Rez.JsonData.pro_21,
        Rez.JsonData.pro_22,
        Rez.JsonData.pro_23,
        Rez.JsonData.pro_24,
        Rez.JsonData.pro_25,
        Rez.JsonData.pro_26,
        Rez.JsonData.pro_27,
        Rez.JsonData.pro_28,
        Rez.JsonData.pro_29,
        Rez.JsonData.pro_30,
        Rez.JsonData.pro_31,
    ] as Array<ResourceId>;

    const MAT_RESOURCES = [
        Rez.JsonData.mat_1,
        Rez.JsonData.mat_2,
        Rez.JsonData.mat_3,
        Rez.JsonData.mat_4,
        Rez.JsonData.mat_5,
        Rez.JsonData.mat_6,
        Rez.JsonData.mat_7,
        Rez.JsonData.mat_8,
        Rez.JsonData.mat_9,
        Rez.JsonData.mat_10,
        Rez.JsonData.mat_11,
        Rez.JsonData.mat_12,
        Rez.JsonData.mat_13,
        Rez.JsonData.mat_14,
        Rez.JsonData.mat_15,
        Rez.JsonData.mat_16,
        Rez.JsonData.mat_17,
        Rez.JsonData.mat_18,
        Rez.JsonData.mat_19,
        Rez.JsonData.mat_20,
        Rez.JsonData.mat_21,
        Rez.JsonData.mat_22,
        Rez.JsonData.mat_23,
        Rez.JsonData.mat_24,
        Rez.JsonData.mat_25,
        Rez.JsonData.mat_26,
        Rez.JsonData.mat_27,
        Rez.JsonData.mat_28,
    ] as Array<ResourceId>;

    const MRK_RESOURCES = [
        Rez.JsonData.mrk_1,
        Rez.JsonData.mrk_2,
        Rez.JsonData.mrk_3,
        Rez.JsonData.mrk_4,
        Rez.JsonData.mrk_5,
        Rez.JsonData.mrk_6,
        Rez.JsonData.mrk_7,
        Rez.JsonData.mrk_8,
        Rez.JsonData.mrk_9,
        Rez.JsonData.mrk_10,
        Rez.JsonData.mrk_11,
        Rez.JsonData.mrk_12,
        Rez.JsonData.mrk_13,
        Rez.JsonData.mrk_14,
        Rez.JsonData.mrk_15,
        Rez.JsonData.mrk_16,
    ] as Array<ResourceId>;

    const LUK_RESOURCES = [
        Rez.JsonData.luk_1,
        Rez.JsonData.luk_2,
        Rez.JsonData.luk_3,
        Rez.JsonData.luk_4,
        Rez.JsonData.luk_5,
        Rez.JsonData.luk_6,
        Rez.JsonData.luk_7,
        Rez.JsonData.luk_8,
        Rez.JsonData.luk_9,
        Rez.JsonData.luk_10,
        Rez.JsonData.luk_11,
        Rez.JsonData.luk_12,
        Rez.JsonData.luk_13,
        Rez.JsonData.luk_14,
        Rez.JsonData.luk_15,
        Rez.JsonData.luk_16,
        Rez.JsonData.luk_17,
        Rez.JsonData.luk_18,
        Rez.JsonData.luk_19,
        Rez.JsonData.luk_20,
        Rez.JsonData.luk_21,
        Rez.JsonData.luk_22,
        Rez.JsonData.luk_23,
        Rez.JsonData.luk_24,
    ] as Array<ResourceId>;

    const JHN_RESOURCES = [
        Rez.JsonData.jhn_1,
        Rez.JsonData.jhn_2,
        Rez.JsonData.jhn_3,
        Rez.JsonData.jhn_4,
        Rez.JsonData.jhn_5,
        Rez.JsonData.jhn_6,
        Rez.JsonData.jhn_7,
        Rez.JsonData.jhn_8,
        Rez.JsonData.jhn_9,
        Rez.JsonData.jhn_10,
        Rez.JsonData.jhn_11,
        Rez.JsonData.jhn_12,
        Rez.JsonData.jhn_13,
        Rez.JsonData.jhn_14,
        Rez.JsonData.jhn_15,
        Rez.JsonData.jhn_16,
        Rez.JsonData.jhn_17,
        Rez.JsonData.jhn_18,
        Rez.JsonData.jhn_19,
        Rez.JsonData.jhn_20,
        Rez.JsonData.jhn_21,
    ] as Array<ResourceId>;

    const ACT_RESOURCES = [
        Rez.JsonData.act_1,
        Rez.JsonData.act_2,
        Rez.JsonData.act_3,
        Rez.JsonData.act_4,
        Rez.JsonData.act_5,
        Rez.JsonData.act_6,
        Rez.JsonData.act_7,
        Rez.JsonData.act_8,
        Rez.JsonData.act_9,
        Rez.JsonData.act_10,
        Rez.JsonData.act_11,
        Rez.JsonData.act_12,
        Rez.JsonData.act_13,
        Rez.JsonData.act_14,
        Rez.JsonData.act_15,
        Rez.JsonData.act_16,
        Rez.JsonData.act_17,
        Rez.JsonData.act_18,
        Rez.JsonData.act_19,
        Rez.JsonData.act_20,
        Rez.JsonData.act_21,
        Rez.JsonData.act_22,
        Rez.JsonData.act_23,
        Rez.JsonData.act_24,
        Rez.JsonData.act_25,
        Rez.JsonData.act_26,
        Rez.JsonData.act_27,
        Rez.JsonData.act_28,
    ] as Array<ResourceId>;

    const ROM_RESOURCES = [
        Rez.JsonData.rom_1,
        Rez.JsonData.rom_2,
        Rez.JsonData.rom_3,
        Rez.JsonData.rom_4,
        Rez.JsonData.rom_5,
        Rez.JsonData.rom_6,
        Rez.JsonData.rom_7,
        Rez.JsonData.rom_8,
        Rez.JsonData.rom_9,
        Rez.JsonData.rom_10,
        Rez.JsonData.rom_11,
        Rez.JsonData.rom_12,
        Rez.JsonData.rom_13,
        Rez.JsonData.rom_14,
        Rez.JsonData.rom_15,
        Rez.JsonData.rom_16,
    ] as Array<ResourceId>;

    const CO1_RESOURCES = [
        Rez.JsonData.co1_1,
        Rez.JsonData.co1_2,
        Rez.JsonData.co1_3,
        Rez.JsonData.co1_4,
        Rez.JsonData.co1_5,
        Rez.JsonData.co1_6,
        Rez.JsonData.co1_7,
        Rez.JsonData.co1_8,
        Rez.JsonData.co1_9,
        Rez.JsonData.co1_10,
        Rez.JsonData.co1_11,
        Rez.JsonData.co1_12,
        Rez.JsonData.co1_13,
        Rez.JsonData.co1_14,
        Rez.JsonData.co1_15,
        Rez.JsonData.co1_16,
    ] as Array<ResourceId>;

    const CO2_RESOURCES = [
        Rez.JsonData.co2_1,
        Rez.JsonData.co2_2,
        Rez.JsonData.co2_3,
        Rez.JsonData.co2_4,
        Rez.JsonData.co2_5,
        Rez.JsonData.co2_6,
        Rez.JsonData.co2_7,
        Rez.JsonData.co2_8,
        Rez.JsonData.co2_9,
        Rez.JsonData.co2_10,
        Rez.JsonData.co2_11,
        Rez.JsonData.co2_12,
        Rez.JsonData.co2_13,
    ] as Array<ResourceId>;

    const GAL_RESOURCES = [
        Rez.JsonData.gal_1,
        Rez.JsonData.gal_2,
        Rez.JsonData.gal_3,
        Rez.JsonData.gal_4,
        Rez.JsonData.gal_5,
        Rez.JsonData.gal_6,
    ] as Array<ResourceId>;

    const EPH_RESOURCES = [
        Rez.JsonData.eph_1,
        Rez.JsonData.eph_2,
        Rez.JsonData.eph_3,
        Rez.JsonData.eph_4,
        Rez.JsonData.eph_5,
        Rez.JsonData.eph_6,
    ] as Array<ResourceId>;

    const PHP_RESOURCES = [
        Rez.JsonData.php_1,
        Rez.JsonData.php_2,
        Rez.JsonData.php_3,
        Rez.JsonData.php_4,
    ] as Array<ResourceId>;

    const COL_RESOURCES = [
        Rez.JsonData.col_1,
        Rez.JsonData.col_2,
        Rez.JsonData.col_3,
        Rez.JsonData.col_4,
    ] as Array<ResourceId>;

    const TH1_RESOURCES = [
        Rez.JsonData.th1_1,
        Rez.JsonData.th1_2,
        Rez.JsonData.th1_3,
        Rez.JsonData.th1_4,
        Rez.JsonData.th1_5,
    ] as Array<ResourceId>;

    const TH2_RESOURCES = [
        Rez.JsonData.th2_1,
        Rez.JsonData.th2_2,
        Rez.JsonData.th2_3,
    ] as Array<ResourceId>;

    const TI1_RESOURCES = [
        Rez.JsonData.ti1_1,
        Rez.JsonData.ti1_2,
        Rez.JsonData.ti1_3,
        Rez.JsonData.ti1_4,
        Rez.JsonData.ti1_5,
        Rez.JsonData.ti1_6,
    ] as Array<ResourceId>;

    const TI2_RESOURCES = [
        Rez.JsonData.ti2_1,
        Rez.JsonData.ti2_2,
        Rez.JsonData.ti2_3,
        Rez.JsonData.ti2_4,
    ] as Array<ResourceId>;

    const TIT_RESOURCES = [
        Rez.JsonData.tit_1,
        Rez.JsonData.tit_2,
        Rez.JsonData.tit_3,
    ] as Array<ResourceId>;

    const PHM_RESOURCES = [
        Rez.JsonData.phm_1,
    ] as Array<ResourceId>;

    const HEB_RESOURCES = [
        Rez.JsonData.heb_1,
        Rez.JsonData.heb_2,
        Rez.JsonData.heb_3,
        Rez.JsonData.heb_4,
        Rez.JsonData.heb_5,
        Rez.JsonData.heb_6,
        Rez.JsonData.heb_7,
        Rez.JsonData.heb_8,
        Rez.JsonData.heb_9,
        Rez.JsonData.heb_10,
        Rez.JsonData.heb_11,
        Rez.JsonData.heb_12,
        Rez.JsonData.heb_13,
    ] as Array<ResourceId>;

    const JAS_RESOURCES = [
        Rez.JsonData.jas_1,
        Rez.JsonData.jas_2,
        Rez.JsonData.jas_3,
        Rez.JsonData.jas_4,
        Rez.JsonData.jas_5,
    ] as Array<ResourceId>;

    const PE1_RESOURCES = [
        Rez.JsonData.pe1_1,
        Rez.JsonData.pe1_2,
        Rez.JsonData.pe1_3,
        Rez.JsonData.pe1_4,
        Rez.JsonData.pe1_5,
    ] as Array<ResourceId>;

    const PE2_RESOURCES = [
        Rez.JsonData.pe2_1,
        Rez.JsonData.pe2_2,
        Rez.JsonData.pe2_3,
    ] as Array<ResourceId>;

    const JN1_RESOURCES = [
        Rez.JsonData.jn1_1,
        Rez.JsonData.jn1_2,
        Rez.JsonData.jn1_3,
        Rez.JsonData.jn1_4,
        Rez.JsonData.jn1_5,
    ] as Array<ResourceId>;

    const JN2_RESOURCES = [
        Rez.JsonData.jn2_1,
    ] as Array<ResourceId>;

    const JN3_RESOURCES = [
        Rez.JsonData.jn3_1,
    ] as Array<ResourceId>;

    const JUD_RESOURCES = [
        Rez.JsonData.jud_1,
    ] as Array<ResourceId>;

    const REV_RESOURCES = [
        Rez.JsonData.rev_1,
        Rez.JsonData.rev_2,
        Rez.JsonData.rev_3,
        Rez.JsonData.rev_4,
        Rez.JsonData.rev_5,
        Rez.JsonData.rev_6,
        Rez.JsonData.rev_7,
        Rez.JsonData.rev_8,
        Rez.JsonData.rev_9,
        Rez.JsonData.rev_10,
        Rez.JsonData.rev_11,
        Rez.JsonData.rev_12,
        Rez.JsonData.rev_13,
        Rez.JsonData.rev_14,
        Rez.JsonData.rev_15,
        Rez.JsonData.rev_16,
        Rez.JsonData.rev_17,
        Rez.JsonData.rev_18,
        Rez.JsonData.rev_19,
        Rez.JsonData.rev_20,
        Rez.JsonData.rev_21,
        Rez.JsonData.rev_22,
    ] as Array<ResourceId>;

    function getResourceId(bookIndex as Number, chapter as Number) as ResourceId? {
                if (bookIndex == 0) {
            if (chapter >= 1 && chapter <= 10) {
                return GEN_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 18) {
            if (chapter >= 1 && chapter <= 150) {
                return PSA_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 19) {
            if (chapter >= 1 && chapter <= 31) {
                return PRO_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 39) {
            if (chapter >= 1 && chapter <= 28) {
                return MAT_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 40) {
            if (chapter >= 1 && chapter <= 16) {
                return MRK_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 41) {
            if (chapter >= 1 && chapter <= 24) {
                return LUK_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 42) {
            if (chapter >= 1 && chapter <= 21) {
                return JHN_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 43) {
            if (chapter >= 1 && chapter <= 28) {
                return ACT_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 44) {
            if (chapter >= 1 && chapter <= 16) {
                return ROM_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 45) {
            if (chapter >= 1 && chapter <= 16) {
                return CO1_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 46) {
            if (chapter >= 1 && chapter <= 13) {
                return CO2_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 47) {
            if (chapter >= 1 && chapter <= 6) {
                return GAL_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 48) {
            if (chapter >= 1 && chapter <= 6) {
                return EPH_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 49) {
            if (chapter >= 1 && chapter <= 4) {
                return PHP_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 50) {
            if (chapter >= 1 && chapter <= 4) {
                return COL_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 51) {
            if (chapter >= 1 && chapter <= 5) {
                return TH1_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 52) {
            if (chapter >= 1 && chapter <= 3) {
                return TH2_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 53) {
            if (chapter >= 1 && chapter <= 6) {
                return TI1_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 54) {
            if (chapter >= 1 && chapter <= 4) {
                return TI2_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 55) {
            if (chapter >= 1 && chapter <= 3) {
                return TIT_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 56) {
            if (chapter >= 1 && chapter <= 1) {
                return PHM_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 57) {
            if (chapter >= 1 && chapter <= 13) {
                return HEB_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 58) {
            if (chapter >= 1 && chapter <= 5) {
                return JAS_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 59) {
            if (chapter >= 1 && chapter <= 5) {
                return PE1_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 60) {
            if (chapter >= 1 && chapter <= 3) {
                return PE2_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 61) {
            if (chapter >= 1 && chapter <= 5) {
                return JN1_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 62) {
            if (chapter >= 1 && chapter <= 1) {
                return JN2_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 63) {
            if (chapter >= 1 && chapter <= 1) {
                return JN3_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 64) {
            if (chapter >= 1 && chapter <= 1) {
                return JUD_RESOURCES[chapter - 1];
            }
                } else if (bookIndex == 65) {
            if (chapter >= 1 && chapter <= 22) {
                return REV_RESOURCES[chapter - 1];
            }
        }
        return null;
    }

    function hasResource(bookIndex as Number, chapter as Number) as Boolean {
        return getResourceId(bookIndex, chapter) != null;
    }

    function getTotalResourceCount() as Number {
        return 451;
    }

}
