#!/usr/bin/env python3
"""
Standalone helper to regenerate BibleResources.mc from existing curated files.
Run after curate_garmin_data.py finishes downloading.
"""

import os
import glob

# Book coverage: (UPPERCASE OSIS code, book_index, start_chapter, end_chapter)
# Must match the COVERAGE table in curate_garmin_data.py exactly.
COVERAGE = [
    ("GEN", 0, 1, 10),
    ("PSA", 18, 1, 150),
    ("PRO", 19, 1, 31),
    ("MAT", 39, 1, 28),
    ("MRK", 40, 1, 16),
    ("LUK", 41, 1, 24),
    ("JHN", 42, 1, 21),
    ("ACT", 43, 1, 28),
    ("ROM", 44, 1, 16),
    ("1CO", 45, 1, 16),
    ("2CO", 46, 1, 13),
    ("GAL", 47, 1, 6),
    ("EPH", 48, 1, 6),
    ("PHP", 49, 1, 4),
    ("COL", 50, 1, 4),
    ("1TH", 51, 1, 5),
    ("2TH", 52, 1, 3),
    ("1TI", 53, 1, 6),
    ("2TI", 54, 1, 4),
    ("TIT", 55, 1, 3),
    ("PHM", 56, 1, 1),
    ("HEB", 57, 1, 13),
    ("JAS", 58, 1, 5),
    ("1PE", 59, 1, 5),
    ("2PE", 60, 1, 3),
    ("1JN", 61, 1, 5),
    ("2JN", 62, 1, 1),
    ("3JN", 63, 1, 1),
    ("JUD", 64, 1, 1),
    ("REV", 65, 1, 22),
]


def _safe_resource_id(osis_lower, chapter):
    """Return a Monkey-C-valid resource id string for a book/chapter.

    Resource ids (and XML attribute ids) must start with a letter.
    Multi-digit book codes like 1co, 2co have the digit moved to the end.
    e.g. 1co_1.json -> co1_1.json -> id="co1_1".
    """
    if osis_lower[0].isdigit():
        return osis_lower[1:] + osis_lower[0] + "_" + str(chapter)
    return osis_lower + "_" + str(chapter)


def _safe_const_name(osis):
    """Return a Monkey-C-valid constant name for the given OSIS code.

    Monkey C identifiers must start with a letter. For multi-word book codes
    like 1CO, 2CO, 1TH, etc., move the leading digit to the end (e.g., CO1).
    """
    if osis[0].isdigit():
        return osis[1:] + osis[0]
    return osis


def generate_bible_resources_mc(source_dir, data_dir, coverage):
    """Generate garmin_bible/source/BibleResources.mc lookup module.

    Also renames JSON files to have valid Monkey C identifiers in their
    filenames (e.g. 1co_1.json -> co1_1.json) and regenerates data.xml.
    """
    import shutil

    # Build lookup: old filename -> safe filename
    rename_map = {}  # old_name -> new_name
    for osis, book_index, start_ch, end_ch in coverage:
        osis_lower = osis.lower()
        for ch in range(start_ch, end_ch + 1):
            old_name = f"{osis_lower}_{ch}.json"
            safe_id = _safe_resource_id(osis_lower, ch)
            new_name = safe_id + ".json"
            if old_name != new_name:
                rename_map[old_name] = new_name

    # Rename files on disk
    renamed = 0
    for old_name, new_name in rename_map.items():
        old_path = os.path.join(data_dir, old_name)
        new_path = os.path.join(data_dir, new_name)
        if os.path.exists(old_path):
            shutil.move(old_path, new_path)
            renamed += 1
    if renamed > 0:
        print(f"Renamed {renamed} resource files to valid identifiers.")

    # Gather resources using safe names
    book_resources = {}
    for osis, book_index, start_ch, end_ch in coverage:
        osis_lower = osis.lower()
        entries = []
        for ch in range(start_ch, end_ch + 1):
            safe_id = _safe_resource_id(osis_lower, ch)
            filepath = os.path.join(data_dir, safe_id + ".json")
            if not os.path.exists(filepath):
                print(f"WARNING: missing {filepath}")
            entries.append((ch, safe_id))
        book_resources[book_index] = entries

    # Generate data.xml with safe ids
    xml_path = os.path.join(data_dir, "data.xml")
    xml_lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
        '    xsi:noNamespaceSchemaLocation="http://developer.garmin.com/downloads/connect-iq/resources.xsd">',
    ]
    for book_index in sorted(book_resources.keys()):
        for ch, safe_id in book_resources[book_index]:
            xml_lines.append(f'    <jsonData id="{safe_id}" filename="{safe_id}.json"/>')
    xml_lines.append("</resources>")
    with open(xml_path, "w", encoding="utf-8") as f:
        f.write("\n".join(xml_lines) + "\n")
    print(f"Generated {xml_path}")

    # Generate BibleResources.mc
    lines = [
        "using Toybox.Application;",
        "import Toybox.Lang;",
        "",
        "// Auto-generated by scripts/curate_garmin_data.py — do not edit manually.",
        "module BibleResources {",
        "",
        "    // Offline coverage: New Testament + Psalms + Proverbs + Genesis 1-10",
        f"    // Total chapters: {sum(end - start + 1 for _, _, start, end in coverage)}",
        "",
    ]

    # Per-book constant arrays of ResourceId
    for book_index in sorted(book_resources.keys()):
        entries = book_resources[book_index]
        osis_code = entries[0][1].split("_")[0].upper()
        const_name = _safe_const_name(osis_code)
        lines.append(f"    const {const_name}_RESOURCES = [")
        for ch, resource_id in entries:
            lines.append(f"        Rez.JsonData.{resource_id},")
        lines.append("    ] as Array<ResourceId>;")
        lines.append("")

    # Helper: getResourceId
    lines.append("    function getResourceId(bookIndex as Number, chapter as Number) as ResourceId? {")
    first = True
    for book_index in sorted(book_resources.keys()):
        entries = book_resources[book_index]
        osis_code = entries[0][1].split("_")[0].upper()
        const_name = _safe_const_name(osis_code)
        max_ch = entries[-1][0]
        prefix = "        if" if first else "        } else if"
        first = False
        lines.append(f"        {prefix} (bookIndex == {book_index}) {{")
        lines.append(f"            if (chapter >= 1 && chapter <= {max_ch}) {{")
        lines.append(f"                return {const_name}_RESOURCES[chapter - 1];")
        lines.append("            }")
    lines.append("        }")
    lines.append("        return null;")
    lines.append("    }")
    lines.append("")

    # Helper: hasResource
    lines.append("    function hasResource(bookIndex as Number, chapter as Number) as Boolean {")
    lines.append("        return getResourceId(bookIndex, chapter) != null;")
    lines.append("    }")
    lines.append("")

    # Helper: totalResourceCount
    lines.append("    function getTotalResourceCount() as Number {")
    total = sum(end - start + 1 for _, _, start, end in coverage)
    lines.append(f"        return {total};")
    lines.append("    }")
    lines.append("")

    lines.append("}")

    mc_path = os.path.join(source_dir, "BibleResources.mc")
    with open(mc_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated {mc_path}")
    return mc_path


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_dir = os.path.join(repo_root, "garmin_bible", "resources", "data")
    source_dir = os.path.join(repo_root, "garmin_bible", "source")
    generate_bible_resources_mc(source_dir, data_dir, COVERAGE)


if __name__ == "__main__":
    main()
