/// Write Flipper-compatible .nfc NDEF URL files for NFC tag sharing.
use alloc::string::String;
use flipperzero_sys as sys;

const NFC_DIR: &str = "/ext/nfc";
const MAX_NFC_FILE: usize = 2048;

fn path_to_cstr(path: &str, buf: &mut [u8; 128]) -> Option<*const core::ffi::c_char> {
    let bytes = path.as_bytes();
    if bytes.len() + 1 > buf.len() {
        return None;
    }
    buf[..bytes.len()].copy_from_slice(bytes);
    buf[bytes.len()] = 0;
    Some(buf.as_ptr() as *const core::ffi::c_char)
}

/// Generate a Flipper .nfc file containing a single NDEF URL record.
/// The file format matches what the Flipper NFC app uses for tag writing.
pub fn write_nfc_file(filename: &str, url: &str) -> bool {
    let mut file_path = String::with_capacity(128);
    file_path.push_str(NFC_DIR);
    file_path.push('/');
    file_path.push_str(filename);
    file_path.push_str(".nfc");

    // Build the .nfc file content
    let mut content = String::with_capacity(1024);
    content.push_str("Filetype: Flipper NFC device\n");
    content.push_str("Version: 3\n");
    content.push_str("# NDEF generated by Bible [BSB]\n");
    content.push_str("Device type: NTAG215\n");
    content.push_str("UID: 04 00 00 00 00 00 00\n");
    content.push_str("ATQA: 00 44\n");
    content.push_str("SAK: 00\n");
    content.push_str("Mifare Classic type: NONE\n");
    content.push_str("Mifare DESFire type: NONE\n");
    content.push_str("NTAG/Ultralight type: NTAG215\n");
    content.push_str("Data format version: 2\n");
    content.push_str("NFC data (NDEF):\n");

    // Build NDEF message manually (Type: URI Record, well-known type)
    let url_bytes = url.as_bytes();
    let payload_len = 1 + url_bytes.len(); // 1 byte prefix + URL

    // Single NDEF record: MB=1, ME=1, SR=1, TNF=01 (Well-known)
    let _header: u8 = 0xD1;
    let _type_len: u8 = 0x01;
    let _payload_len_byte: u8 = payload_len as u8;
    let _type_name: u8 = 0x55; // 'U' = URI
    let uri_prefix: u8 = 0x02; // https://

    content.push_str("  Record 1\n");
    content.push_str("    Type: URI\n");
    content.push_str("    TNF: Well-known\n");
    content.push_str("    ID: \n");
    content.push_str("    Payload (hex): ");

    // Payload hex: URI prefix byte + URL bytes
    let mut first = true;
    {
        let &b = &uri_prefix;
        if !first {
            content.push(' ');
        }
        first = false;
        content.push_str(&byte_to_hex(b));
    }
    for &b in url_bytes {
        if !first {
            content.push(' ');
        }
        first = false;
        content.push_str(&byte_to_hex(b));
    }
    content.push('\n');
    content.push_str("NDEF Stop\n");

    // Write to SD card
    let mut path_buf = [0u8; 128];
    let path_c = match path_to_cstr(&file_path, &mut path_buf) {
        Some(p) => p,
        None => return false,
    };

    unsafe {
        let storage = sys::furi_record_open(c"storage".as_ptr() as *const u8);
        if storage.is_null() {
            return false;
        }

        // Ensure directory exists (best effort)
        let mut dir_buf = [0u8; 128];
        let dir_c = {
            let bytes = NFC_DIR.as_bytes();
            dir_buf[..bytes.len()].copy_from_slice(bytes);
            dir_buf[bytes.len()] = 0;
            dir_buf.as_ptr() as *const core::ffi::c_char
        };
        sys::storage_common_mkdir(storage as *mut sys::Storage, dir_c);

        let file = sys::storage_file_alloc(storage as *mut sys::Storage);
        if file.is_null() {
            sys::furi_record_close(c"storage".as_ptr() as *const u8);
            return false;
        }

        let opened = sys::storage_file_open(file, path_c, sys::FSAM_WRITE, sys::FSOM_OPEN_ALWAYS);
        if !opened {
            sys::storage_file_close(file);
            sys::storage_file_free(file);
            sys::furi_record_close(c"storage".as_ptr() as *const u8);
            return false;
        }

        let written = sys::storage_file_write(
            file,
            content.as_ptr() as *const core::ffi::c_void,
            content.len(),
        );
        sys::storage_file_close(file);
        sys::storage_file_free(file);
        sys::furi_record_close(c"storage".as_ptr() as *const core::ffi::c_char);

        if written == content.len() {
            let loader = sys::furi_record_open(c"loader".as_ptr() as *const core::ffi::c_char)
                as *mut sys::Loader;
            if !loader.is_null() {
                sys::loader_start_with_gui_error(
                    loader,
                    c"nfc".as_ptr() as *const core::ffi::c_char,
                    path_c,
                );
                sys::furi_record_close(c"loader".as_ptr() as *const core::ffi::c_char);
            }
            true
        } else {
            false
        }
    }
}

fn byte_to_hex(b: u8) -> String {
    let hex = *b"0123456789ABCDEF";
    let mut s = String::with_capacity(2);
    s.push(hex[(b >> 4) as usize] as char);
    s.push(hex[(b & 0x0F) as usize] as char);
    s
}
